export const Industries = {
    COAL_MINE: "coal_mine",
    IRON_WORKS: "iron_works",
    BREWERY: "brewery",
    COTTON_MILL: "cotton_mill",
    MANUFACTURER: "manufacturer",
    POTTERY: "pottery",
};

export const Cities = {
    BIRMINGHAM: "birmingham",
    CONVENTRY: "conventry",
    KIDDMINSTER: "kiddminster",
};

export const CITIES = [
    {
        name: "birmingham",
        industrySlots: [
            [Industries.COTTON_MILL, Industries.MANUFACTURER],
            [Industries.IRON_WORKS],
            [Industries.MANUFACTURER],
            [Industries.MANUFACTURER],
        ],
    },
    {
        name: "conventry",
        industrySlots: [
            [Industries.POTTERY],
            [Industries.IRON_WORKS],
            [Industries.COAL_MINE],
        ],
    },
];

export const CitySlotTypes = {
    INDUSTRY: "industry",
    MERCHANT: "merchant",
};

export const CITY_SLOTS = [
    { type: "industry", location: ["berby", 0], position: [2867, 942] },
    { type: "industry", location: ["berby", 1], position: [3054, 942] },
    { type: "industry", location: ["berby", 2], position: [2960, 754] },
    { type: "industry", location: ["birmingham", 0], position: [2338, 2717] },
    { type: "industry", location: ["birmingham", 1], position: [2524, 2717] },
    { type: "industry", location: ["birmingham", 2], position: [2338, 2529] },
    { type: "industry", location: ["birmingham", 3], position: [2524, 2529] },
    { type: "industry", location: ["stone", 0], position: [1053, 918] },
    { type: "industry", location: ["stone", 1], position: [1238, 918] },
    { type: "industry", location: ["walsall", 0], position: [1947, 2163] },
    { type: "industry", location: ["walsall", 1], position: [2132, 2163] },
    { type: "industry", location: ["burton_upon_trent", 0], position: [2556, 1410] },
    { type: "industry", location: ["burton_upon_trent", 1], position: [2742, 1410] },
    { type: "industry", location: ["wolverhampton", 0], position: [1302, 2071] },
    { type: "industry", location: ["wolverhampton", 1], position: [1486, 2071] },
    { type: "industry", location: ["stafford", 0], position: [1425, 1293] },
    { type: "industry", location: ["stafford", 1], position: [1613, 1293] },
    { type: "industry", location: ["cannock", 0], position: [1722, 1703] },
    { type: "industry", location: ["cannock", 1], position: [1906, 1703] },
    { type: "industry", location: ["tamworth", 0], position: [2616, 1911] },
    { type: "industry", location: ["tamworth", 1], position: [2797, 1911] },
    { type: "industry", location: ["stoke_on_trent", 0], position: [1470, 495] },
    { type: "industry", location: ["stoke_on_trent", 1], position: [1658, 495] },
    { type: "industry", location: ["stoke_on_trent", 2], position: [1564, 309] },
    { type: "industry", location: ["coventry", 0], position: [3067, 2843] },
    { type: "industry", location: ["coventry", 1], position: [3254, 2843] },
    { type: "industry", location: ["coventry", 2], position: [3160, 2655] },
    { type: "industry", location: ["dudley", 0], position: [1487, 2562] },
    { type: "industry", location: ["dudley", 1], position: [1672, 2562] },
    { type: "industry", location: ["uttoxeter", 0], position: [2083, 849] },
    { type: "industry", location: ["uttoxeter", 1], position: [2272, 849] },
    { type: "industry", location: ["coalbrookdale", 0], position: [750, 2247] },
    { type: "industry", location: ["coalbrookdale", 1], position: [936, 2247] },
    { type: "industry", location: ["coalbrookdale", 2], position: [843, 2059] },
    { type: "industry", location: ["kidderminster", 0], position: [1208, 2975] },
    { type: "industry", location: ["kidderminster", 1], position: [1394, 2975] },
    { type: "industry", location: ["worcester", 0], position: [1260, 3494] },
    { type: "industry", location: ["worcester", 1], position: [1448, 3494] },
    { type: "industry", location: ["leek", 0], position: [2034, 205] },
    { type: "industry", location: ["leek", 1], position: [2221, 205] },
    { type: "industry", location: ["belper", 0], position: [2739, 264] },
    { type: "industry", location: ["belper", 1], position: [2926, 264] },
    { type: "industry", location: ["belper", 2], position: [3112, 264] },
    { type: "industry", location: ["redditch", 0], position: [2150, 3189] },
    { type: "industry", location: ["redditch", 1], position: [2339, 3189] },
    { type: "industry", location: ["nuneaton", 0], position: [2976, 2315] },
    { type: "industry", location: ["nuneaton", 1], position: [3164, 2315] },
    { type: "industry", location: ["anonymous_1", 0], position: [1108, 1653] },
    { type: "industry", location: ["anonymous_2", 0], position: [952, 3275] },
    { type: "merchant", location: ["warrington", 0], position: [933, 426] },
    { type: "merchant", location: ["warrington", 1], position: [1122, 426] },
    { type: "merchant", location: ["nottingham", 0], position: [3437, 680] },
    { type: "merchant", location: ["nottingham", 1], position: [3625, 680] },
    { type: "merchant", location: ["oxford", 0], position: [3127, 3328] },
    { type: "merchant", location: ["oxford", 1], position: [3314, 3328] },
    { type: "merchant", location: ["gloucester", 0], position: [2238, 3632] },
    { type: "merchant", location: ["gloucester", 1], position: [2422, 3632] },
    { type: "merchant", location: ["shrewsbury", 0], position: [269, 2268] },
];

export const LINKS = [
    { uid: 1, head: "warrington", tail: "stoke_on_trent", position: [1351, 364], eras: [true, true] },
    { uid: 2, head: "stoke_on_trent", tail: "leek", position: [1825, 299], eras: [true, true] },
    { uid: 3, head: "stoke_on_trent", tail: "stone", position: [1399, 814], eras: [true, true] },
    { uid: 4, head: "leek", tail: "belper", position: [2515, 251], eras: [false, true] },
    { uid: 5, head: "belper", tail: "derby", position: [2994, 602], eras: [true, true] },
    { uid: 6, head: "stone", tail: "uttoxeter", position: [1681, 933], eras: [false, true] },
    { uid: 7, head: "stone", tail: "burton_on_trent", position: [1940, 1149], eras: [true, true] },
    { uid: 8, head: "stone", tail: "stafford", position: [1187, 1296], eras: [true, true] },
    { uid: 9, head: "uttoxeter", tail: "derby", position: [2591, 984], eras: [false, true] },
    { uid: 10, head: "derby", tail: "nottingham", position: [3211, 801], eras: [true, true] },
    { uid: 11, head: "derby", tail: "burton_on_trent", position: [2974, 1281], eras: [true, true] },
    { uid: 12, head: "stafford", tail: "cannock", position: [1838, 1533], eras: [true, true] },
    { uid: 13, head: "burton_on_trent", tail: "cannock", position: [2267, 1533], eras: [false, true] },
    { uid: 14, head: "cannock", tail: "anonymous_1", position: [1439, 1704], eras: [true, true] },
    { uid: 15, head: "cannock", tail: "wolverhampton", position: [1520, 1902], eras: [true, true] },
    { uid: 16, head: "cannock", tail: "walsall", position: [2102, 1994], eras: [true, true] },
    { uid: 17, head: "burton_on_trent", tail: "walsall", position: [2297, 1859], eras: [true, false] },
    { uid: 18, head: "burton_on_trent", tail: "tamworth", position: [2735, 1757], eras: [true, true] },
    { uid: 19, head: "shrewsbury", tail: "coalbrookdale", position: [600, 2129], eras: [true, true] },
    { uid: 20, head: "coalbrookdale", tail: "wolverhampton", position: [1097, 2129], eras: [true, true] },
    { uid: 21, head: "wolverhampton", tail: "walsall", position: [1748, 2157], eras: [true, true] },
    { uid: 22, head: "walsall", tail: "tamworth", position: [2453, 2178], eras: [false, true] },
    { uid: 23, head: "coalbrookdale", tail: "kidderminster", position: [942, 2742], eras: [true, true] },
    { uid: 24, head: "wolverhampton", tail: "dudley", position: [1428, 2421], eras: [true, true] },
    { uid: 25, head: "walsall", tail: "birmingham", position: [2154, 2511], eras: [true, true] },
    { uid: 26, head: "tamworth", tail: "birmingham", position: [2718, 2331], eras: [true, true] },
    { uid: 27, head: "tamworth", tail: "nuneaton", position: [3065, 2082], eras: [true, true] },
    { uid: 28, head: "kidderminster", tail: "dudley", position: [1347, 2819], eras: [true, true] },
    { uid: 29, head: "dudley", tail: "birmingham", position: [2012, 2681], eras: [true, true] },
    { uid: 30, head: "nuneaton", tail: "birmingham", position: [2792, 2556], eras: [false, true] },
    { uid: 31, head: "nuneaton", tail: "coventry", position: [3388, 2589], eras: [false, true] },
    { uid: 32, head: "birmingham", tail: "coventry", position: [2816, 2868], eras: [true, true] },
    { uid: 33, head: "kidderminster", tail: "worcester", position: [1300, 3330], eras: [true, true] },
    { uid: 34, head: "worcester", tail: "birmingham", position: [1884, 3113], eras: [true, true] },
    { uid: 35, head: "birmingham", tail: "redditch", position: [2396, 3046], eras: [false, true] },
    { uid: 36, head: "birmingham", tail: "oxford", position: [2808, 3054], eras: [true, true] },
    { uid: 37, head: "worcester", tail: "gloucester", position: [1700, 3679], eras: [true, true] },
    { uid: 38, head: "gloucester", tail: "redditch", position: [1956, 3417], eras: [true, true] },
    { uid: 39, head: "redditch", tail: "oxford", position: [2592, 3309], eras: [true, true] },
];