import Random from "../../../libs/math/Random";
import Orb from "../orb/Orb";
import World from "../World";

export default interface OrbGenerator {
    generate(world: World, random?: Random): Orb;
}

export const ORB_NAMES = [
    "Saturn",
    "Saturnus",
    "Ops",
    "Pikus",
    "Faunus",
    "Fauna",
    "Vesta",
    "Larentia",
    "Volsker",
    "Kakus",
    "Mars",
    "Bellona",
    "Anna",
    "Minewa",
    "Apollo",
    "Venus",
    "Vwetunus",
    "Erebus",
    "Diana",
    "Juturna",
    "Egeria",
    "Oedipus",
    "Neptun",
    "Portunus",
    "Pluto",
    "Manen",
    "Lemuren",
    "Fortuna",
    "Mercury",
    "Janus",
    "Leres",
    "Augur",
    "Evander",
    "Chimare",
    "Fides",
    "Furien",
    "Heracles",
    "Kentaure",
    "Konkordia",
    "Marsfeld",
    "Musen",
    "Nereiden",
    "Nymphen",
    "Orkus",
    "Penaten",
    "Pamona",
    "Sirenen",
    "Vitoria",
];